listen: :9090
log_file: stdout
log_level: debug
locations:
  - description: "Add rpm"
    filename_re: rpm$
    uri: /pkg/CentOS/7/Packages
    save_path: /tmp/
    sync: false
    bash_exec_timeout: 30
    bash_exec: |
      expect <<EOD
      spawn bash -c "rpm --addsign /tmp/%filename%"
      expect "Enter pass phrase:"
      send "\r"
      expect eof
      EOD
      mv -f /tmp/%filename% /srv/www/repo/pkg/CentOS/7/Packages/%filename%
      createrepo --update /srv/www/repo/pkg/CentOS/7 || exit 1

  - description: "Add zip"
    filename_re: zip$
    uri: /pkg/zip
    sync: true
    save_path: /srv/www/repo/pkg/zip
    bash_exec: |
      cd /srv/www/repo/pkg/zip || exit 1
      sha256sum %filename% > %filename%.sha256 || exit 1
